[2025-04-01T04:36:37.314+0000] {taskinstance.py:1125} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: covertype_workflow.train_models manual__2025-04-01T04:31:09.883653+00:00 [queued]>
[2025-04-01T04:36:37.380+0000] {taskinstance.py:1125} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: covertype_workflow.train_models manual__2025-04-01T04:31:09.883653+00:00 [queued]>
[2025-04-01T04:36:37.382+0000] {taskinstance.py:1331} INFO - Starting attempt 2 of 2
[2025-04-01T04:36:37.466+0000] {taskinstance.py:1350} INFO - Executing <Task(PythonOperator): train_models> on 2025-04-01 04:31:09.883653+00:00
[2025-04-01T04:36:37.560+0000] {standard_task_runner.py:57} INFO - Started process 524 to run task
[2025-04-01T04:36:37.588+0000] {standard_task_runner.py:84} INFO - Running: ['***', 'tasks', 'run', 'covertype_workflow', 'train_models', 'manual__2025-04-01T04:31:09.883653+00:00', '--job-id', '103', '--raw', '--subdir', 'DAGS_FOLDER/covertype_workflow.py', '--cfg-path', '/tmp/tmp7l6vmgey']
[2025-04-01T04:36:37.597+0000] {standard_task_runner.py:85} INFO - Job 103: Subtask train_models
[2025-04-01T04:36:37.902+0000] {task_command.py:410} INFO - Running <TaskInstance: covertype_workflow.train_models manual__2025-04-01T04:31:09.883653+00:00 [running]> on host fa1ab66db115
[2025-04-01T04:36:38.411+0000] {taskinstance.py:1570} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='covertype_workflow' AIRFLOW_CTX_TASK_ID='train_models' AIRFLOW_CTX_EXECUTION_DATE='2025-04-01T04:31:09.883653+00:00' AIRFLOW_CTX_TRY_NUMBER='2' AIRFLOW_CTX_DAG_RUN_ID='manual__2025-04-01T04:31:09.883653+00:00'
[2025-04-01T04:36:38.488+0000] {covertype_workflow.py:183} INFO - `covertype_preprocessed` NO existe. Omitiendo entrenamiento.
[2025-04-01T04:36:38.488+0000] {python.py:183} INFO - Done. Returned value was: None
[2025-04-01T04:36:38.559+0000] {taskinstance.py:1373} INFO - Marking task as SUCCESS. dag_id=covertype_workflow, task_id=train_models, execution_date=20250401T043109, start_date=20250401T043637, end_date=20250401T043638
[2025-04-01T04:36:38.705+0000] {local_task_job_runner.py:232} INFO - Task exited with return code 0
[2025-04-01T04:36:38.899+0000] {taskinstance.py:2674} INFO - 0 downstream tasks scheduled from follow-on schedule check
